# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66471ff60b8ad8ece0c04e7f8f450248d669b8ab7a36ac7d041b5c20a8926559483c7f7b6d653a3879efce724758f5a1b9e5f41e37e83b55c2f10aab97b98eb0

test:
  secret_key_base: 7db74e4c42f88f4212ca1d2e448d07d0aeb70ab561fcf6aaa422fc03301d0e0d793395d51b95b2924717c0a8a11616e9a58ff6acd8bdc4ab5fe22691122b2b18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
